// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech.proto

package com.tyg.speech.rpc;

public final class SpeechProto {
  private SpeechProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SpeechRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:speech.SpeechRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes audio_data = 1;</code>
     * @return The audioData.
     */
    com.google.protobuf.ByteString getAudioData();

    /**
     * <pre>
     * 语言代码如"zh-CN"
     * </pre>
     *
     * <code>string language = 2;</code>
     * @return The language.
     */
    java.lang.String getLanguage();
    /**
     * <pre>
     * 语言代码如"zh-CN"
     * </pre>
     *
     * <code>string language = 2;</code>
     * @return The bytes for language.
     */
    com.google.protobuf.ByteString
        getLanguageBytes();

    /**
     * <pre>
     * 采样率
     * </pre>
     *
     * <code>int32 sample_rate = 3;</code>
     * @return The sampleRate.
     */
    int getSampleRate();

    /**
     * <pre>
     * 是否返回中间结果
     * </pre>
     *
     * <code>optional bool interim_results = 4;</code>
     * @return Whether the interimResults field is set.
     */
    boolean hasInterimResults();
    /**
     * <pre>
     * 是否返回中间结果
     * </pre>
     *
     * <code>optional bool interim_results = 4;</code>
     * @return The interimResults.
     */
    boolean getInterimResults();
  }
  /**
   * Protobuf type {@code speech.SpeechRequest}
   */
  public static final class SpeechRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:speech.SpeechRequest)
      SpeechRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SpeechRequest.newBuilder() to construct.
    private SpeechRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SpeechRequest() {
      audioData_ = com.google.protobuf.ByteString.EMPTY;
      language_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SpeechRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tyg.speech.rpc.SpeechProto.internal_static_speech_SpeechRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tyg.speech.rpc.SpeechProto.internal_static_speech_SpeechRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tyg.speech.rpc.SpeechProto.SpeechRequest.class, com.tyg.speech.rpc.SpeechProto.SpeechRequest.Builder.class);
    }

    private int bitField0_;
    public static final int AUDIO_DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString audioData_;
    /**
     * <code>bytes audio_data = 1;</code>
     * @return The audioData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAudioData() {
      return audioData_;
    }

    public static final int LANGUAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object language_;
    /**
     * <pre>
     * 语言代码如"zh-CN"
     * </pre>
     *
     * <code>string language = 2;</code>
     * @return The language.
     */
    @java.lang.Override
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        language_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 语言代码如"zh-CN"
     * </pre>
     *
     * <code>string language = 2;</code>
     * @return The bytes for language.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SAMPLE_RATE_FIELD_NUMBER = 3;
    private int sampleRate_;
    /**
     * <pre>
     * 采样率
     * </pre>
     *
     * <code>int32 sample_rate = 3;</code>
     * @return The sampleRate.
     */
    @java.lang.Override
    public int getSampleRate() {
      return sampleRate_;
    }

    public static final int INTERIM_RESULTS_FIELD_NUMBER = 4;
    private boolean interimResults_;
    /**
     * <pre>
     * 是否返回中间结果
     * </pre>
     *
     * <code>optional bool interim_results = 4;</code>
     * @return Whether the interimResults field is set.
     */
    @java.lang.Override
    public boolean hasInterimResults() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 是否返回中间结果
     * </pre>
     *
     * <code>optional bool interim_results = 4;</code>
     * @return The interimResults.
     */
    @java.lang.Override
    public boolean getInterimResults() {
      return interimResults_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!audioData_.isEmpty()) {
        output.writeBytes(1, audioData_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(language_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, language_);
      }
      if (sampleRate_ != 0) {
        output.writeInt32(3, sampleRate_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(4, interimResults_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!audioData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, audioData_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(language_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, language_);
      }
      if (sampleRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, sampleRate_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, interimResults_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tyg.speech.rpc.SpeechProto.SpeechRequest)) {
        return super.equals(obj);
      }
      com.tyg.speech.rpc.SpeechProto.SpeechRequest other = (com.tyg.speech.rpc.SpeechProto.SpeechRequest) obj;

      if (!getAudioData()
          .equals(other.getAudioData())) return false;
      if (!getLanguage()
          .equals(other.getLanguage())) return false;
      if (getSampleRate()
          != other.getSampleRate()) return false;
      if (hasInterimResults() != other.hasInterimResults()) return false;
      if (hasInterimResults()) {
        if (getInterimResults()
            != other.getInterimResults()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AUDIO_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getAudioData().hashCode();
      hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
      hash = (53 * hash) + getLanguage().hashCode();
      hash = (37 * hash) + SAMPLE_RATE_FIELD_NUMBER;
      hash = (53 * hash) + getSampleRate();
      if (hasInterimResults()) {
        hash = (37 * hash) + INTERIM_RESULTS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getInterimResults());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tyg.speech.rpc.SpeechProto.SpeechRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tyg.speech.rpc.SpeechProto.SpeechRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code speech.SpeechRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:speech.SpeechRequest)
        com.tyg.speech.rpc.SpeechProto.SpeechRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tyg.speech.rpc.SpeechProto.internal_static_speech_SpeechRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tyg.speech.rpc.SpeechProto.internal_static_speech_SpeechRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tyg.speech.rpc.SpeechProto.SpeechRequest.class, com.tyg.speech.rpc.SpeechProto.SpeechRequest.Builder.class);
      }

      // Construct using com.tyg.speech.rpc.SpeechProto.SpeechRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        audioData_ = com.google.protobuf.ByteString.EMPTY;

        language_ = "";

        sampleRate_ = 0;

        interimResults_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tyg.speech.rpc.SpeechProto.internal_static_speech_SpeechRequest_descriptor;
      }

      @java.lang.Override
      public com.tyg.speech.rpc.SpeechProto.SpeechRequest getDefaultInstanceForType() {
        return com.tyg.speech.rpc.SpeechProto.SpeechRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.tyg.speech.rpc.SpeechProto.SpeechRequest build() {
        com.tyg.speech.rpc.SpeechProto.SpeechRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tyg.speech.rpc.SpeechProto.SpeechRequest buildPartial() {
        com.tyg.speech.rpc.SpeechProto.SpeechRequest result = new com.tyg.speech.rpc.SpeechProto.SpeechRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.audioData_ = audioData_;
        result.language_ = language_;
        result.sampleRate_ = sampleRate_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.interimResults_ = interimResults_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tyg.speech.rpc.SpeechProto.SpeechRequest) {
          return mergeFrom((com.tyg.speech.rpc.SpeechProto.SpeechRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tyg.speech.rpc.SpeechProto.SpeechRequest other) {
        if (other == com.tyg.speech.rpc.SpeechProto.SpeechRequest.getDefaultInstance()) return this;
        if (other.getAudioData() != com.google.protobuf.ByteString.EMPTY) {
          setAudioData(other.getAudioData());
        }
        if (!other.getLanguage().isEmpty()) {
          language_ = other.language_;
          onChanged();
        }
        if (other.getSampleRate() != 0) {
          setSampleRate(other.getSampleRate());
        }
        if (other.hasInterimResults()) {
          setInterimResults(other.getInterimResults());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                audioData_ = input.readBytes();

                break;
              } // case 10
              case 18: {
                language_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 24: {
                sampleRate_ = input.readInt32();

                break;
              } // case 24
              case 32: {
                interimResults_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString audioData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes audio_data = 1;</code>
       * @return The audioData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAudioData() {
        return audioData_;
      }
      /**
       * <code>bytes audio_data = 1;</code>
       * @param value The audioData to set.
       * @return This builder for chaining.
       */
      public Builder setAudioData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        audioData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes audio_data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAudioData() {
        
        audioData_ = getDefaultInstance().getAudioData();
        onChanged();
        return this;
      }

      private java.lang.Object language_ = "";
      /**
       * <pre>
       * 语言代码如"zh-CN"
       * </pre>
       *
       * <code>string language = 2;</code>
       * @return The language.
       */
      public java.lang.String getLanguage() {
        java.lang.Object ref = language_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          language_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 语言代码如"zh-CN"
       * </pre>
       *
       * <code>string language = 2;</code>
       * @return The bytes for language.
       */
      public com.google.protobuf.ByteString
          getLanguageBytes() {
        java.lang.Object ref = language_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          language_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 语言代码如"zh-CN"
       * </pre>
       *
       * <code>string language = 2;</code>
       * @param value The language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        language_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 语言代码如"zh-CN"
       * </pre>
       *
       * <code>string language = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLanguage() {
        
        language_ = getDefaultInstance().getLanguage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 语言代码如"zh-CN"
       * </pre>
       *
       * <code>string language = 2;</code>
       * @param value The bytes for language to set.
       * @return This builder for chaining.
       */
      public Builder setLanguageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        language_ = value;
        onChanged();
        return this;
      }

      private int sampleRate_ ;
      /**
       * <pre>
       * 采样率
       * </pre>
       *
       * <code>int32 sample_rate = 3;</code>
       * @return The sampleRate.
       */
      @java.lang.Override
      public int getSampleRate() {
        return sampleRate_;
      }
      /**
       * <pre>
       * 采样率
       * </pre>
       *
       * <code>int32 sample_rate = 3;</code>
       * @param value The sampleRate to set.
       * @return This builder for chaining.
       */
      public Builder setSampleRate(int value) {
        
        sampleRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 采样率
       * </pre>
       *
       * <code>int32 sample_rate = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSampleRate() {
        
        sampleRate_ = 0;
        onChanged();
        return this;
      }

      private boolean interimResults_ ;
      /**
       * <pre>
       * 是否返回中间结果
       * </pre>
       *
       * <code>optional bool interim_results = 4;</code>
       * @return Whether the interimResults field is set.
       */
      @java.lang.Override
      public boolean hasInterimResults() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 是否返回中间结果
       * </pre>
       *
       * <code>optional bool interim_results = 4;</code>
       * @return The interimResults.
       */
      @java.lang.Override
      public boolean getInterimResults() {
        return interimResults_;
      }
      /**
       * <pre>
       * 是否返回中间结果
       * </pre>
       *
       * <code>optional bool interim_results = 4;</code>
       * @param value The interimResults to set.
       * @return This builder for chaining.
       */
      public Builder setInterimResults(boolean value) {
        bitField0_ |= 0x00000001;
        interimResults_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否返回中间结果
       * </pre>
       *
       * <code>optional bool interim_results = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearInterimResults() {
        bitField0_ = (bitField0_ & ~0x00000001);
        interimResults_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:speech.SpeechRequest)
    }

    // @@protoc_insertion_point(class_scope:speech.SpeechRequest)
    private static final com.tyg.speech.rpc.SpeechProto.SpeechRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tyg.speech.rpc.SpeechProto.SpeechRequest();
    }

    public static com.tyg.speech.rpc.SpeechProto.SpeechRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SpeechRequest>
        PARSER = new com.google.protobuf.AbstractParser<SpeechRequest>() {
      @java.lang.Override
      public SpeechRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SpeechRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SpeechRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tyg.speech.rpc.SpeechProto.SpeechRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SpeechResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:speech.SpeechResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string text = 1;</code>
     * @return The text.
     */
    java.lang.String getText();
    /**
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <pre>
     * 是否为最终结果
     * </pre>
     *
     * <code>bool is_final = 2;</code>
     * @return The isFinal.
     */
    boolean getIsFinal();

    /**
     * <pre>
     * 置信度
     * </pre>
     *
     * <code>float confidence = 3;</code>
     * @return The confidence.
     */
    float getConfidence();

    /**
     * <pre>
     * 其他可能的识别结果
     * </pre>
     *
     * <code>repeated string alternatives = 4;</code>
     * @return A list containing the alternatives.
     */
    java.util.List<java.lang.String>
        getAlternativesList();
    /**
     * <pre>
     * 其他可能的识别结果
     * </pre>
     *
     * <code>repeated string alternatives = 4;</code>
     * @return The count of alternatives.
     */
    int getAlternativesCount();
    /**
     * <pre>
     * 其他可能的识别结果
     * </pre>
     *
     * <code>repeated string alternatives = 4;</code>
     * @param index The index of the element to return.
     * @return The alternatives at the given index.
     */
    java.lang.String getAlternatives(int index);
    /**
     * <pre>
     * 其他可能的识别结果
     * </pre>
     *
     * <code>repeated string alternatives = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the alternatives at the given index.
     */
    com.google.protobuf.ByteString
        getAlternativesBytes(int index);
  }
  /**
   * Protobuf type {@code speech.SpeechResponse}
   */
  public static final class SpeechResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:speech.SpeechResponse)
      SpeechResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SpeechResponse.newBuilder() to construct.
    private SpeechResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SpeechResponse() {
      text_ = "";
      alternatives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SpeechResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tyg.speech.rpc.SpeechProto.internal_static_speech_SpeechResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tyg.speech.rpc.SpeechProto.internal_static_speech_SpeechResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tyg.speech.rpc.SpeechProto.SpeechResponse.class, com.tyg.speech.rpc.SpeechProto.SpeechResponse.Builder.class);
    }

    public static final int TEXT_FIELD_NUMBER = 1;
    private volatile java.lang.Object text_;
    /**
     * <code>string text = 1;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 1;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_FINAL_FIELD_NUMBER = 2;
    private boolean isFinal_;
    /**
     * <pre>
     * 是否为最终结果
     * </pre>
     *
     * <code>bool is_final = 2;</code>
     * @return The isFinal.
     */
    @java.lang.Override
    public boolean getIsFinal() {
      return isFinal_;
    }

    public static final int CONFIDENCE_FIELD_NUMBER = 3;
    private float confidence_;
    /**
     * <pre>
     * 置信度
     * </pre>
     *
     * <code>float confidence = 3;</code>
     * @return The confidence.
     */
    @java.lang.Override
    public float getConfidence() {
      return confidence_;
    }

    public static final int ALTERNATIVES_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList alternatives_;
    /**
     * <pre>
     * 其他可能的识别结果
     * </pre>
     *
     * <code>repeated string alternatives = 4;</code>
     * @return A list containing the alternatives.
     */
    public com.google.protobuf.ProtocolStringList
        getAlternativesList() {
      return alternatives_;
    }
    /**
     * <pre>
     * 其他可能的识别结果
     * </pre>
     *
     * <code>repeated string alternatives = 4;</code>
     * @return The count of alternatives.
     */
    public int getAlternativesCount() {
      return alternatives_.size();
    }
    /**
     * <pre>
     * 其他可能的识别结果
     * </pre>
     *
     * <code>repeated string alternatives = 4;</code>
     * @param index The index of the element to return.
     * @return The alternatives at the given index.
     */
    public java.lang.String getAlternatives(int index) {
      return alternatives_.get(index);
    }
    /**
     * <pre>
     * 其他可能的识别结果
     * </pre>
     *
     * <code>repeated string alternatives = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the alternatives at the given index.
     */
    public com.google.protobuf.ByteString
        getAlternativesBytes(int index) {
      return alternatives_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
      }
      if (isFinal_ != false) {
        output.writeBool(2, isFinal_);
      }
      if (java.lang.Float.floatToRawIntBits(confidence_) != 0) {
        output.writeFloat(3, confidence_);
      }
      for (int i = 0; i < alternatives_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, alternatives_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(text_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
      }
      if (isFinal_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isFinal_);
      }
      if (java.lang.Float.floatToRawIntBits(confidence_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, confidence_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < alternatives_.size(); i++) {
          dataSize += computeStringSizeNoTag(alternatives_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAlternativesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tyg.speech.rpc.SpeechProto.SpeechResponse)) {
        return super.equals(obj);
      }
      com.tyg.speech.rpc.SpeechProto.SpeechResponse other = (com.tyg.speech.rpc.SpeechProto.SpeechResponse) obj;

      if (!getText()
          .equals(other.getText())) return false;
      if (getIsFinal()
          != other.getIsFinal()) return false;
      if (java.lang.Float.floatToIntBits(getConfidence())
          != java.lang.Float.floatToIntBits(
              other.getConfidence())) return false;
      if (!getAlternativesList()
          .equals(other.getAlternativesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (37 * hash) + IS_FINAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsFinal());
      hash = (37 * hash) + CONFIDENCE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getConfidence());
      if (getAlternativesCount() > 0) {
        hash = (37 * hash) + ALTERNATIVES_FIELD_NUMBER;
        hash = (53 * hash) + getAlternativesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tyg.speech.rpc.SpeechProto.SpeechResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.tyg.speech.rpc.SpeechProto.SpeechResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tyg.speech.rpc.SpeechProto.SpeechResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code speech.SpeechResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:speech.SpeechResponse)
        com.tyg.speech.rpc.SpeechProto.SpeechResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tyg.speech.rpc.SpeechProto.internal_static_speech_SpeechResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tyg.speech.rpc.SpeechProto.internal_static_speech_SpeechResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tyg.speech.rpc.SpeechProto.SpeechResponse.class, com.tyg.speech.rpc.SpeechProto.SpeechResponse.Builder.class);
      }

      // Construct using com.tyg.speech.rpc.SpeechProto.SpeechResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        text_ = "";

        isFinal_ = false;

        confidence_ = 0F;

        alternatives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tyg.speech.rpc.SpeechProto.internal_static_speech_SpeechResponse_descriptor;
      }

      @java.lang.Override
      public com.tyg.speech.rpc.SpeechProto.SpeechResponse getDefaultInstanceForType() {
        return com.tyg.speech.rpc.SpeechProto.SpeechResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.tyg.speech.rpc.SpeechProto.SpeechResponse build() {
        com.tyg.speech.rpc.SpeechProto.SpeechResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tyg.speech.rpc.SpeechProto.SpeechResponse buildPartial() {
        com.tyg.speech.rpc.SpeechProto.SpeechResponse result = new com.tyg.speech.rpc.SpeechProto.SpeechResponse(this);
        int from_bitField0_ = bitField0_;
        result.text_ = text_;
        result.isFinal_ = isFinal_;
        result.confidence_ = confidence_;
        if (((bitField0_ & 0x00000001) != 0)) {
          alternatives_ = alternatives_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.alternatives_ = alternatives_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tyg.speech.rpc.SpeechProto.SpeechResponse) {
          return mergeFrom((com.tyg.speech.rpc.SpeechProto.SpeechResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tyg.speech.rpc.SpeechProto.SpeechResponse other) {
        if (other == com.tyg.speech.rpc.SpeechProto.SpeechResponse.getDefaultInstance()) return this;
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        if (other.getIsFinal() != false) {
          setIsFinal(other.getIsFinal());
        }
        if (other.getConfidence() != 0F) {
          setConfidence(other.getConfidence());
        }
        if (!other.alternatives_.isEmpty()) {
          if (alternatives_.isEmpty()) {
            alternatives_ = other.alternatives_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAlternativesIsMutable();
            alternatives_.addAll(other.alternatives_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                text_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 16: {
                isFinal_ = input.readBool();

                break;
              } // case 16
              case 29: {
                confidence_ = input.readFloat();

                break;
              } // case 29
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureAlternativesIsMutable();
                alternatives_.add(s);
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 1;</code>
       * @return The text.
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       * @return The bytes for text.
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       * @param value The text to set.
       * @return This builder for chaining.
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       * @param value The bytes for text to set.
       * @return This builder for chaining.
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }

      private boolean isFinal_ ;
      /**
       * <pre>
       * 是否为最终结果
       * </pre>
       *
       * <code>bool is_final = 2;</code>
       * @return The isFinal.
       */
      @java.lang.Override
      public boolean getIsFinal() {
        return isFinal_;
      }
      /**
       * <pre>
       * 是否为最终结果
       * </pre>
       *
       * <code>bool is_final = 2;</code>
       * @param value The isFinal to set.
       * @return This builder for chaining.
       */
      public Builder setIsFinal(boolean value) {
        
        isFinal_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否为最终结果
       * </pre>
       *
       * <code>bool is_final = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsFinal() {
        
        isFinal_ = false;
        onChanged();
        return this;
      }

      private float confidence_ ;
      /**
       * <pre>
       * 置信度
       * </pre>
       *
       * <code>float confidence = 3;</code>
       * @return The confidence.
       */
      @java.lang.Override
      public float getConfidence() {
        return confidence_;
      }
      /**
       * <pre>
       * 置信度
       * </pre>
       *
       * <code>float confidence = 3;</code>
       * @param value The confidence to set.
       * @return This builder for chaining.
       */
      public Builder setConfidence(float value) {
        
        confidence_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 置信度
       * </pre>
       *
       * <code>float confidence = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearConfidence() {
        
        confidence_ = 0F;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList alternatives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAlternativesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          alternatives_ = new com.google.protobuf.LazyStringArrayList(alternatives_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 其他可能的识别结果
       * </pre>
       *
       * <code>repeated string alternatives = 4;</code>
       * @return A list containing the alternatives.
       */
      public com.google.protobuf.ProtocolStringList
          getAlternativesList() {
        return alternatives_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 其他可能的识别结果
       * </pre>
       *
       * <code>repeated string alternatives = 4;</code>
       * @return The count of alternatives.
       */
      public int getAlternativesCount() {
        return alternatives_.size();
      }
      /**
       * <pre>
       * 其他可能的识别结果
       * </pre>
       *
       * <code>repeated string alternatives = 4;</code>
       * @param index The index of the element to return.
       * @return The alternatives at the given index.
       */
      public java.lang.String getAlternatives(int index) {
        return alternatives_.get(index);
      }
      /**
       * <pre>
       * 其他可能的识别结果
       * </pre>
       *
       * <code>repeated string alternatives = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the alternatives at the given index.
       */
      public com.google.protobuf.ByteString
          getAlternativesBytes(int index) {
        return alternatives_.getByteString(index);
      }
      /**
       * <pre>
       * 其他可能的识别结果
       * </pre>
       *
       * <code>repeated string alternatives = 4;</code>
       * @param index The index to set the value at.
       * @param value The alternatives to set.
       * @return This builder for chaining.
       */
      public Builder setAlternatives(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAlternativesIsMutable();
        alternatives_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 其他可能的识别结果
       * </pre>
       *
       * <code>repeated string alternatives = 4;</code>
       * @param value The alternatives to add.
       * @return This builder for chaining.
       */
      public Builder addAlternatives(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAlternativesIsMutable();
        alternatives_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 其他可能的识别结果
       * </pre>
       *
       * <code>repeated string alternatives = 4;</code>
       * @param values The alternatives to add.
       * @return This builder for chaining.
       */
      public Builder addAllAlternatives(
          java.lang.Iterable<java.lang.String> values) {
        ensureAlternativesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, alternatives_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 其他可能的识别结果
       * </pre>
       *
       * <code>repeated string alternatives = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlternatives() {
        alternatives_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 其他可能的识别结果
       * </pre>
       *
       * <code>repeated string alternatives = 4;</code>
       * @param value The bytes of the alternatives to add.
       * @return This builder for chaining.
       */
      public Builder addAlternativesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAlternativesIsMutable();
        alternatives_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:speech.SpeechResponse)
    }

    // @@protoc_insertion_point(class_scope:speech.SpeechResponse)
    private static final com.tyg.speech.rpc.SpeechProto.SpeechResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tyg.speech.rpc.SpeechProto.SpeechResponse();
    }

    public static com.tyg.speech.rpc.SpeechProto.SpeechResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SpeechResponse>
        PARSER = new com.google.protobuf.AbstractParser<SpeechResponse>() {
      @java.lang.Override
      public SpeechResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SpeechResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SpeechResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tyg.speech.rpc.SpeechProto.SpeechResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_SpeechRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_SpeechRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_SpeechResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_SpeechResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014speech.proto\022\006speech\"|\n\rSpeechRequest\022" +
      "\022\n\naudio_data\030\001 \001(\014\022\020\n\010language\030\002 \001(\t\022\023\n" +
      "\013sample_rate\030\003 \001(\005\022\034\n\017interim_results\030\004 " +
      "\001(\010H\000\210\001\001B\022\n\020_interim_results\"Z\n\016SpeechRe" +
      "sponse\022\014\n\004text\030\001 \001(\t\022\020\n\010is_final\030\002 \001(\010\022\022" +
      "\n\nconfidence\030\003 \001(\002\022\024\n\014alternatives\030\004 \003(\t" +
      "2\221\001\n\006Speech\022<\n\tRecognize\022\025.speech.Speech" +
      "Request\032\026.speech.SpeechResponse\"\000\022I\n\022Str" +
      "eamingRecognize\022\025.speech.SpeechRequest\032\026" +
      ".speech.SpeechResponse\"\000(\0010\001B!\n\022com.tyg." +
      "speech.rpcB\013SpeechProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_speech_SpeechRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_speech_SpeechRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_SpeechRequest_descriptor,
        new java.lang.String[] { "AudioData", "Language", "SampleRate", "InterimResults", "InterimResults", });
    internal_static_speech_SpeechResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_speech_SpeechResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_SpeechResponse_descriptor,
        new java.lang.String[] { "Text", "IsFinal", "Confidence", "Alternatives", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
